# Generated by Django 5.2.6 on 2025-10-16 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='days_streak',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дней подряд'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Интересы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_level',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Уровень владения языка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_goals',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Цель изучения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons_completed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уроков пройдено'),
        ),
        migrations.AddField(
            model_name='profile',
            name='words_learned',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Выученных слов'),
        ),
    ]
