# Generated by Django 5.2.6 on 2025-10-19 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Present Simple', max_length=200, verbose_name='Название блока')),
                ('description', models.TextField(help_text='Изучение настоящего времени', verbose_name='Описание')),
                ('level', models.CharField(choices=[('A1', 'A1 - Начальный'), ('A2', 'A2 - Элементарный'), ('B1', 'B1 - Средний'), ('B2', 'B2 - Выше среднего'), ('C1', 'C1 - Продвинутый'), ('C2', 'C2 - Профессиональный')], max_length=2, verbose_name='Уровень CEFR')),
                ('difficulty_level', models.IntegerField(help_text='Сложность внутри уровня', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Сложность (1-5)')),
                ('grammar_topic', models.CharField(help_text='Например: present_simple', max_length=100, verbose_name='Грамматическая тема')),
                ('order', models.IntegerField(help_text='Порядок блока в последовательности', verbose_name='Порядковый номер')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Все уроки пройдены')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Все уроки на 80%+')),
                ('completion_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Блок уроков',
                'verbose_name_plural': 'Блоки уроков',
                'ordering': ['user', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('grammar', 'Грамматика'), ('vocabulary', 'Лексика'), ('reading', 'Чтение')], max_length=20, verbose_name='Тип урока')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('content', models.JSONField(help_text='Структура контента в JSON', verbose_name='Контент урока')),
                ('order', models.IntegerField(help_text='1 - грамматика, 2 - лексика, 3 - чтение', verbose_name='Порядок в блоке')),
                ('estimated_time', models.IntegerField(default=15, verbose_name='Примерное время (мин)')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='Разблокирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lessonblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['block', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Лучший результат (%)')),
                ('current_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Текущий результат (%)')),
                ('exercises_data', models.JSONField(default=dict, help_text='{"ex1": {"answer": "...", "is_correct": true}}', verbose_name='Данные упражнений')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('attempts', models.IntegerField(default=0, verbose_name='Попыток')),
                ('words_learned_count', models.IntegerField(default=0, help_text='Только для vocabulary', verbose_name='Выучено слов')),
                ('first_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Первое завершение')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Последний доступ')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс урока',
                'verbose_name_plural': 'Прогресс уроков',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.AddIndex(
            model_name='lessonblock',
            index=models.Index(fields=['user', 'order'], name='lessons_les_user_id_f32743_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonblock',
            index=models.Index(fields=['user', 'is_completed'], name='lessons_les_user_id_bcd2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['block', 'order'], name='lessons_les_block_i_478e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='lessons_les_user_id_21e7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'is_completed'], name='lessons_les_user_id_844587_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
    ]
